input_text = (f"Hospitalized patient of age {inputs.age} getting worse has labs"
            f"and vitals values of systolic blood pressure {inputs.sbp_impute:.2f} mmHg"
            f"diastolic blood pressure {inputs.dbp_impute:.2f} mmHg, pulse pressure index "
            f"{inputs.ppi_impute:.2f} , oxygen saturation {inputs.o2sat_impute:.2f} %, body temperature "
            f"{inputs.temp_c_impute:.2f} celcius degree, avpu {inputs.avpu_impute:.2f} , albumin "
            f"{inputs.albumin_impute:.2f} g/dL, alkaline phoshatase {inputs.alk_phos_impute:.2f} U/L,"
            f"anion gap {inputs.anion_gap_impute:.2f} mmol/L, bilirubin total {inputs.bili_total_impute:.2f} mg/dL,"
            f"blood urea nitrogen {inputs.bun_impute:.2f} mg/dL, blood urea nitroge cr ratio "
            f"{inputs.bun_cr_ratio_impute:.2f} mg/g, calcium {inputs.calcium_impute:.2f}, chloride "
            f"{inputs.chloride:.2f} mmol/L, carbon dioxide {inputs.co2_impute:.2f} mmol/L,"
            f"creatinine {inputs.creatinine_impute:.2f} mg/dL, glucose serum {inputs.gluc_ser_impute:.2f} mg/dL,"
            f"hemoglobin {inputs.hb_impute:.2f} g/dL, platelet count {inputs.platelet_count_impute:.2f},"
            f"potassium {inputs.potassium_impute:.2f} mmol/L, serum glutamin-oxaloacetic transaminase "
            f"{inputs.sgot_impute:.2f}, sodium {inputs.sodium_impute:.2f} mmol/L, total protein "
            f"{inputs.total_protein_impute:.2f} g/dL, white blood cell {inputs.wbc_impute:.2f}."
            f"Does the patient have {target_diagnosis}? ")
            
    input_text = (f"Hospitalized patient of age {inputs.age} getting worse has labs"
            f"and vitals values of systolic blood pressure {inputs.sbp_impute:.2f} mmHg"
            f"diastolic blood pressure {inputs.dbp_impute:.2f} mmHg, pulse pressure index "
            f"{inputs.ppi_impute:.2f} , oxygen saturation {inputs.o2sat_impute:.2f} %, body temperature "
            f"{inputs.temp_c_impute:.2f} celcius degree, avpu {inputs.avpu_impute:.2f} , albumin "
            f"{inputs.albumin_impute:.2f} g/dL, alkaline phoshatase {inputs.alk_phos_impute:.2f} U/L,"
            f"anion gap {inputs.anion_gap_impute:.2f} mmol/L, bilirubin total {inputs.bili_total_impute:.2f} mg/dL,"
            f"blood urea nitrogen {inputs.bun_impute:.2f} mg/dL, blood urea nitroge cr ratio "
            f"{inputs.bun_cr_ratio_impute:.2f} mg/g, calcium {inputs.calcium_impute:.2f}, chloride "
            f"{inputs.chloride:.2f} mmol/L, carbon dioxide {inputs.co2_impute:.2f} mmol/L,"
            f"creatinine {inputs.creatinine_impute:.2f} mg/dL, glucose serum {inputs.gluc_ser_impute:.2f} mg/dL,"
            f"hemoglobin {inputs.hb_impute:.2f} g/dL, platelet count {inputs.platelet_count_impute:.2f},"
            f"potassium {inputs.potassium_impute:.2f} mmol/L, serum glutamin-oxaloacetic transaminase "
            f"{inputs.sgot_impute:.2f}, sodium {inputs.sodium_impute:.2f} mmol/L, total protein "
            f"{inputs.total_protein_impute:.2f} g/dL, white blood cell {inputs.wbc_impute:.2f}."
            f"Does the patient have {target_diagnosis}? ")
